credentials:
  usernames:
    nguyenvana:
      email: nguyenvana@example.com
      name: nguyenvana
      password: $2b$12$RafoCiWmAk1ZbV8kS8tKye8Zza9s6KtjYMmfMphi6zg3ubyfrcfW.
    tranthib:
      email: tranthib@example.com
      name: tranthib
      password: $2b$12$RafoCiWmAk1ZbV8kS8tKye8Zza9s6KtjYMmfMphi6zg3ubyfrcfW.
cookie:
  expiry_days: 7
  key: dummy_key_will_be_replaced_by_secrets
  name: tuan_tra_cookie
